### ISSUE TITLE
Connection is not kept in background

### ISSUE THREAD

**Issue by JulienPalard** [glowing-bear/glowing-bear-cordova#13]
- Android 7.1.2
- Glowing Near 0.6.0

I'd like the app to stay connected in background to get notifications, but it does not like to do survive for long in the background, I never get notifications and I see the "connecting…" page almost each time I open the app.

**Comment by lorenzhs** [comment]
Your system is killing it because it's out of memory. Nothing we can do about that. A truly native client could have a service in the background that maintains the connection. On the other hand, keeping a connection open drains the battery. It's probably a better idea to use something like [irssinotifier](https://irssinotifier.appspot.com/) (also works with weechat) or [pushover](https://pushover.net/) for notifications.
