### ISSUE TITLE
Cannot build for iOS

### ISSUE THREAD

**Issue by altf4arnold** [glowing-bear/glowing-bear-cordova#17]
Hello, 

I was trying to build the app for iOS. but I'm getting this error message : 
```
error: /Users/arnold/glowing-bear-cordova/platforms/ios/CordovaLib/Cordova/Cordova.h: No such file or directory (in target 'Cordova' from project 'CordovaLib')
```
I installed cordova but apparently, the cordova plugin restore seems to lead to nothing

**Comment by lorenzhs** [comment]
This may not be what you want to hear, but Glowing Bear's cordova app has been abandoned. We withdrew the app from the Play Store a few years ago because we couldn't maintain it any more. So even if you could build it, you would get a rather old version of Glowing Bear. You could try Safari's "add to homescreen" functionality instead.
